import csv
import json
import os
import random
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

import bcrypt
from faker import Faker

OUTPUT_DIR = Path("../init_data")
OUTPUT_DIR.mkdir(exist_ok=True)

with open("map_data.json", encoding="utf-8") as f:
    DATA = json.load(f)

fake = Faker("es_MX") # save data in spanish

user_agency_list = []
user_buyer_list = []
properties_list = []
requests_list = []
reviews_list = []


# ── Helpers ───────────────────────────────────────────────────────────────────
def rand_date(days_back: int) -> datetime:
    """Fecha aleatoria dentro de los últimos N días, con zona horaria en centro america (UTC-6)."""
    delta = random.randint(0, days_back)
    # Zona horaria de Centro América (UTC-6)
    ca_tz = timezone(timedelta(hours=-6))
    return datetime.now(ca_tz) - timedelta(days=delta)

def rand_location() -> dict:
    """Returns a dict with province, city y district."""
    return random.choice(DATA["cr_locations"])

def rand_property_type() -> str:
    """Returns a random type of property based on weights/relevance define for the type of property."""
    types   = list(DATA["property_weights"].keys())
    weights = list(DATA["property_weights"].values())
    return random.choices(types, weights=weights, k=1)[0]

def rand_coords(province: str) -> tuple:
    """Aproximated coordinates for Costa Rica provinces."""
    coords = {
        "San José":   (9.93,  -84.08, 0.15),
        "Alajuela":   (10.02, -84.21, 0.20),
        "Heredia":    (10.00, -84.12, 0.15),
        "Cartago":    (9.86,  -83.92, 0.15),
        "Guanacaste": (10.33, -85.55, 0.40),
        "Puntarenas": (9.98,  -84.83, 0.50),
        "Limón":      (9.99,  -83.03, 0.30),
    }
    base_lat, base_lng, spread = coords.get(province, (9.93, -84.08, 0.2))
    lat = round(base_lat + random.uniform(-spread, spread), 7)
    lng = round(base_lng + random.uniform(-spread, spread), 7)
    return lat, lng

def build_property_title(ptype: str, location: dict, area: float, beds: int, floor: int) -> str:
    template = random.choice(DATA["property_title_templates"][ptype])
    return template.format(
        city     = location["city"],
        district = location["district"],
        province = location["province"],
        beds     = beds or random.randint(1, 5),
        floor    = floor or random.randint(2, 20),
        area     = area,
        unit     = f"{random.choice('ABCD')}-{random.randint(101, 420)}",
        name     = random.choice(DATA["condo_names"]),
    )

def image_urls(seed: str, count: int = 5) -> list[dict]:
    """Generate consistent picsum URLs for a property."""
    return [
        {"url": f"https://picsum.photos/seed/{seed}-{i}/1200/800", "order": i}
        for i in range(count)
    ]

def write_csv(name, fields, rows):
    path = OUTPUT_DIR / name
    file_exists = os.path.exists(path)
    with open(path, "a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        if not file_exists:
            w.writeheader()
        w.writerows(rows)
    print(f"  ✓ {name:38s} {len(rows):>4} filas")

def clean_output_dir():
    for old in OUTPUT_DIR.glob("*.csv"):
        old.unlink()


# ── Seeders ───────────────────────────────────────────────────────────────────
def seed_agencies():
    """Inserts records of agencies in csvs for user and profile data."""
    print("  → Seeding agencies...")
    agencies = DATA["agency_names"]

    rows_user_agency = []
    rows_agency_profile = []
    for i, agency in enumerate(agencies):
        user_id = str(uuid.uuid4())
        name = agency["name"]
        email = f"{name.lower().replace(' ', '')}.ventas@gmail.com"
        password = bcrypt.hashpw(agency["password"].encode(), bcrypt.gensalt()).decode()
        loc = rand_location()
        created = rand_date(random.randrange(500,1000))

        user_agency_list.append({"id": user_id, "name": name, "email": email})

        rows_user_agency.append({
            "id": user_id,
            "email": email,
            "password": password,
            "role": "agency",
            "created_at": created,
            "updated_at": created,
        })

        # despite de id can be autogenerated, the agency user one is created for using it later
        rows_agency_profile.append({
            "user_id": user_id,
            "agency_name": name,
            "description": fake.paragraph(nb_sentences=2),
            "website_url": f"https://www.{name.lower().replace(' ', '')}.com",
            "phone": fake.numerify("2#######"), # show in frontend as 2###-####
            "email_contact": email,
            "country": "Costa Rica",
            "city": loc["city"],
            "address": fake.street_address(),
            "founded_year": random.randint(1990, 2020),
            "is_verified": i < 3,
            "created_at": created,
            "updated_at": created,
        })
    
    write_csv("users.csv", rows_user_agency[0].keys(), rows_user_agency)
    write_csv("agency_profiles.csv", rows_agency_profile[0].keys(), rows_agency_profile)


def seed_buyers(count: int = 60):
    """Inserts records of buyers in csvs for user and profile data."""
    print("  → Seeding buyers...")

    rows_user_buyer = []
    rows_buyer_profile = []
    for _ in range(count):
        user_id = str(uuid.uuid4())
        first_name = fake.first_name()
        last_name = fake.last_name()
        name = first_name + " " + last_name
        email = f"{name.lower().replace(' ', '')}.buyer@gmail.com"
        password = bcrypt.hashpw(b"password123", bcrypt.gensalt()).decode()
        loc = rand_location()
        avatar_url = f"https://ui-avatars.com/api/?name={user_id}&size=150&background=random"
        created = rand_date(random.randrange(100,500))

        user_buyer_list.append({"id": user_id, "name": name, "email": email})
        
        rows_user_buyer.append({
            "id": user_id,
            "email": email,
            "password": password,
            "role": "user",
            "created_at": created,
            "updated_at": created,
        })

        # despite de id can be autogenerated, the buyer user one is created for using it later
        rows_buyer_profile.append({
            "user_id": user_id,
            "first_name": first_name,
            "last_name": last_name,
            "phone": str(random.randint(6,8)) + fake.numerify("#######"),
            "avatar_url": avatar_url,
            "bio": f"{fake.catch_phrase()} — {fake.sentence(nb_words=random.randint(8, 15))}",
            "country": "Costa Rica",
            "city": loc["city"],
            "created_at": created,
            "updated_at": created,
        })
        
    write_csv("users.csv", rows_user_buyer[0].keys(), rows_user_buyer)
    write_csv("buyer_profiles.csv", rows_buyer_profile[0].keys(), rows_buyer_profile)


def seed_properties(count: int = 80):
    """Inserts properties into a csv and saves some records info for later."""
    print("  → Seeding properties...")
    
    statuses = ["available"] * 70 + ["sold_out"] * 20 + ["paused"] * 10
    price_ranges = DATA["price_ranges_usd"]
    area_ranges = DATA["area_ranges_m2"]

    properties = []
    for _ in range(count):
        prop_id = str(uuid.uuid4())
        agency_user_id = random.choice(user_agency_list).get("id")

        ptype = rand_property_type()
        loc = rand_location()
        province, city, district = loc
        lat, lng = rand_coords(province)
        
        description = fake.paragraph(nb_sentences=4)
        status = random.choice(statuses)

        price_min, price_max = price_ranges[ptype].values()
        currency = random.choice(["USD", "CRC", "CRC"])
        if currency == "CRC":
            price_min *= 450
            price_max *= 450
        price = round(random.randint(price_min // 1000, price_max // 1000) * 1000, 2)
        area_min, area_max = area_ranges[ptype].values()
        area_m2 = round(random.uniform(area_min, area_max), 2)
        published_at = rand_date(random.randrange(250, 500))

        # Rooms, floors and bathrooms are only present in some types of properties
        has_rooms = ptype in ("house", "apartment", "condominium")
        bedrooms = random.randint(2, 5) if has_rooms else 0
        bathrooms = random.randint(1, max(1, bedrooms or 1)) if has_rooms or ptype == "commercial" else 0
        parking = random.randint(0, 3) if ptype != "land" else 0
        if ptype in ("house", "condominium", "commercial"):
            floor_num = None
            total_floors = random.randint(1,2)
        elif ptype == "apartment":
            floor_num = random.randint(1, 25)
            total_floors = random.randint(floor_num, floor_num+15)
        else:
            floor_num = None
            total_floors = 0
        year_built = random.randint(1990, 2024) if ptype != "land" else None

        title = build_property_title(ptype, loc, area_m2, bedrooms, total_floors)
        properties_list.append({
            "id": prop_id,
            "title": title,
            "status": status,
            "price": price,
            "currency": currency,
            "agency_user_id": agency_user_id,
            "published_at": published_at,   # save the date for approval email log
        })

        properties.append({
            "id": prop_id,
            "agency_user_id": agency_user_id,
            "title": title,
            "description": description,
            "property_type": ptype,
            "status": status,
            "price": price,
            "currency": currency,
            "area_m2": area_m2,
            "bedrooms": bedrooms,
            "bathrooms": bathrooms,
            "parking_spots": parking,
            "floor_number": floor_num,
            "total_floors": total_floors,
            "year_built": year_built,
            "province": province,
            "city": city,
            "district": district,
            "address": fake.street_address(),
            "latitude": lat,
            "longitude": lng,
            "has_pool": random.random() < 0.3 if ptype != "land" else False,  # has_pool  (30%)
            "has_gym": random.random() < 0.2 if ptype != "land" else False,  # has_gym   (20%)
            "has_garden": random.random() < 0.4 if ptype != "land" else False,  # has_garden(40%)
            "is_featured": random.random() < 0.1,  # is_featured(10%)
            "views_count": random.randint(0, 800),
            "published_at": published_at,
            "updated_at": published_at,
        })

    write_csv("properties.csv", properties[0].keys(), properties)


def seed_property_images():
    """Inserts images for each property."""
    print("  → Seeding images for properties...")

    property_images = []
    for prop in properties_list:
        count = random.randint(5, 15)
        for img in image_urls(prop["id"], count):
            property_images.append({
                "property_id": prop["id"],
                "url": img["url"],
                "display_order": img["order"], # the 0 one is used for the preface
            })

    write_csv("property_images.csv", property_images[0].keys(), property_images)


def seed_reviews():
    """Inserts reviews in a csv and save some records info for later seeding. Each buyer can only review an agency once, but can be edited later, in web."""
    print("  → Seeding reviews...")

    # Random sample of pairs (buyer, agency) without repeating
    pairs = set() # unique pairs set
    target = min(len(user_buyer_list) * 2, len(user_buyer_list) * len(user_agency_list))

    attempts = 0
    while len(pairs) < target and attempts < target * 3: # make pairs
        pair = (random.choice(user_buyer_list).get("id"), random.choice(user_agency_list).get("id"))
        pairs.add(pair)
        attempts += 1

    reviews = []
    review_titles = DATA["review_titles"]
    review_bodies = DATA["review_bodies"]
    for buyer_id, agency_id in pairs:
        # id is generate so it can be used later
        review_id = str(uuid.uuid4())
        rating = random.choices([1, 2, 3, 4, 5], weights=[3, 5, 12, 45, 35], k=1)[0]
        created = rand_date(300)
        edited = random.random() < 0.15  # 15% were edited
        updated = rand_date(50) if edited else created
        title = random.choice(review_titles)

        reviews_list.append({
            "id": review_id,
            "agency_user_id": agency_id,
            "buyer_user_id": buyer_id,
            "title": title,
            "created_at": created,
        })

        reviews.append({
            "id": review_id,
            "agency_user_id": agency_id,
            "buyer_user_id": buyer_id,
            "rating": rating,
            "title": title,
            "body": random.choice(review_bodies) if random.random() > 0.1 else None,
            "is_visible": random.random() > 0.05,  # 95% visibles
            "created_at": created,
            "updated_at": updated,
        })

    write_csv("agency_reviews.csv", reviews[0].keys(), reviews)


def seed_purchase_requests():
    """
    Inserts properties purchase requests.
    Only available and sold_out (maybe a request was send before being blocked, or many requests and needs to choose one buyer) can have requests.
    """
    print("  → Seeding purchase requests...")

    # Take a sample of properties to asociate requests
    eligible = [p for p in properties_list if p["status"] in ("available", "sold_out")]
    sample = random.sample(eligible, min(40, len(eligible)))

    # To avoid breaking the EXCLUDE constraint (1 active per property)
    active_properties = set()

    purchase_requests = []
    rejection_reasons = DATA["rejection_reasons"]
    for prop in sample:
        buyer_id = random.choice(user_buyer_list).get("id")

        # It has an active request?
        if prop["id"] in active_properties:
            # Only allow historical records (cancelled)
            status = "cancelled"
        else:
            status = random.choices(
                ["pending", "accepted", "rejected", "cancelled"],
                weights=[35, 40, 20, 5],
                k=1,
            )[0]
            if status in ("pending", "accepted"):
                active_properties.add(prop["id"])

        req_id = str(uuid.uuid4())
        requested_at = rand_date(100)
        responded_at = (
            requested_at + timedelta(days=random.randint(1, 10))
            if status != "pending"
            else None
        )
        rejection = random.choice(rejection_reasons) if status == "rejected" else None
        requests_list.append({
                "id": req_id,
                "buyer_id": buyer_id,
                "agency_user_id": prop["agency_user_id"],
                "property_id": prop["id"],
                "property_title": prop["title"],
                "status": status,
                "requested_at": requested_at, # to use date on emails
                "responded_at": responded_at,
        })

        purchase_requests.append({
            "id": req_id,
            "property_id": prop["id"],
            "buyer_user_id": buyer_id,
            "status": status,
            "message": fake.sentence() if random.random() > 0.3 else None,
            "rejection_reason": rejection,
            "price_at_request": prop["price"],
            "currency_at_request": prop["currency"],
            "buyer_notified": status != "pending",  # notify if it has had an answer
            "agency_notified": True,                # agency notified about user requests (an other emails related to the agency)
            "requested_at": requested_at,
            "responded_at": responded_at,
            "created_at": requested_at,
            "updated_at": responded_at or requested_at,
        })


    write_csv("purchase_requests.csv", purchase_requests[0].keys(), purchase_requests)


def seed_email_logs():
    """Inserts email logs derivates from requests (purchase, publish, welcome)."""
    print("  → Seeding email logs...")

    email_logs = []
    email_templates = DATA["email_templates"]
    agencies_by_id = {a["id"]: a for a in user_agency_list}
    buyers_by_id = {b["id"]: b for b in user_buyer_list}
    
    def log_email(receiver_email, user_id, subject, template,
                  related_entity=None, related_id=None, days_back=100,
                  success_rate=0.97, created=None):
        success = random.random() < success_rate
        created = created or rand_date(days_back)
        email_logs.append({
            "receiver_email": receiver_email,
            "receiver_user_id": user_id,
            "subject": subject,
            "template_name": template,
            "related_entity": related_entity,
            "related_id": related_id, # uuid from request
            "sent_at": created if success else None,
            "error_message": None if success else "SMTP connection timeout",
            "success": success,
            "created_at": created,
        })

    # WELCOME Emails (sample of buyers)
    welcome_sample = random.sample(user_buyer_list, min(20, len(user_buyer_list)))
    for buyer in welcome_sample:
        log_email(
            buyer["email"], buyer["id"],
            email_templates["welcome_buyer"].format(name=buyer["name"]),
            "welcome_buyer", "welcome", days_back=100, success_rate=0.98,
        )

    # WELCOME Emails (agencias)
    for agency in user_agency_list:
        log_email(
            agency["email"], agency["id"],
            email_templates["welcome_agency"].format(agency=agency["name"]),
            "welcome_agency", "welcome", days_back=450, success_rate=0.98,
        )

    # PUBLISH _APPROVE Email (when agency publish a property and the request is approved).
    # Fechado con el published_at real de la propiedad.
    for prop in properties_list:
        agency = agencies_by_id[prop["agency_user_id"]]
        log_email(agency["email"], agency["id"],
                    email_templates["agency_post_approve"].format(title=prop["title"]),
                    "agency_post_approve", "property", prop["id"],
                    created=prop["published_at"]) # using the real published date of the property created before
    
    # REVIEW Email (notify the agency it has been reviewed by an user).
    for review in reviews_list:
        agency = agencies_by_id[review["agency_user_id"]]
        buyer = buyers_by_id[review["buyer_user_id"]]
        log_email(agency["email"], agency["id"],
                    email_templates["agency_new_review"].format(
                        buyer=buyer["name"], title=review["title"]),
                    "agency_new_review", "agency_review", review["id"],
                    created=review["created_at"]) # using the real created date of the review saved before
    
    # PURCHASE_REQUESTS Emails (for each request)
    for req in requests_list:
        buyer = buyers_by_id[req["buyer_id"]]
        agency = agencies_by_id[req["agency_user_id"]]
        title = req["property_title"]
        days_back = random.randint(10, 50)

        # Confirmation to the buyer + notify agency
        log_email(buyer["email"], buyer["id"],
                  email_templates["purchase_received"].format(title=title),
                  "purchase_received", "purchase_request", req["id"], days_back=days_back)
        log_email(agency["email"], agency["id"],
                  email_templates["agency_new_request"].format(title=title),
                  "agency_new_request", "purchase_request", req["id"], days_back=days_back)

        # It was responded
        days_back = random.randint(3,10)
        if req["status"] == "accepted":
            log_email(buyer["email"], buyer["id"],
                      email_templates["purchase_accepted"].format(title=title),
                      "purchase_accepted", "purchase_request", req["id"], days_back=days_back)
        elif req["status"] == "rejected":
            log_email(buyer["email"], buyer["id"],
                      email_templates["purchase_rejected"].format(title=title),
                      "purchase_rejected", "purchase_request", req["id"], days_back=days_back)

    write_csv("email_logs.csv", email_logs[0].keys(), email_logs)


# ── Main ──────────────────────────────────────────────────────────────────────
def run():
    print("🌱 PropView — generating seed CSVs...\n")
    
    clean_output_dir()

    print("\n📦 Creating data...\n")
    seed_agencies()
    seed_buyers()
    seed_properties()
    seed_property_images()
    seed_reviews()
    seed_purchase_requests()
    seed_email_logs()
    
    print(f"""
✅ CSVs generated in {OUTPUT_DIR.resolve()}

Users created
├── Agencies  : {len(user_agency_list)}
├── Buyers    : {len(user_buyer_list)}

Data generated
├── Properties  : {len(properties_list)}
└── Requests    : {len(requests_list)}
""")


if __name__ == "__main__":
    run()